In [8]:
import numpy
#numpy is a library that makes it easy to work with arrays
from keras.datasets import mnist
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import Dropout
from keras.layers import Flatten
from keras.layers.convolutional import Conv2D
from keras.layers.convolutional import MaxPooling2D
from keras.optimizers import Adam
from keras.utils import np_utils

In [9]:
#load all of the data
(X_train,y_train),(X_test,y_test) = mnist.load_data()

In [11]:
X_train.shape # so we have 60k examples of 28X28 arrays, each representing a number

(60000, 28, 28)

In [12]:
y_train.shape #these are the labels of the labled dataset (supervised learning)

(60000,)

In [23]:
for i in range(10):
    print(y_train[i])

[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
[0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
[0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
[0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
[0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [19]:
X_train.shape

(60000, 28, 28, 1)

In [20]:
X_test = X_test.reshape(X_test.shape[0], X_test.shape[1], X_test.shape[2], 1).astype('float32')

In [21]:
# normalize inputs from 0-255 to 0-1
X_train/=255
X_test/=255

In [22]:
# one hot encode
number_of_classes = 10
y_train = np_utils.to_categorical(y_train, number_of_classes)
y_test = np_utils.to_categorical(y_test, number_of_classes)

In [24]:
#this creates the actual model
model = Sequential()
model.add(Conv2D(32,(5,5),input_shape=(X_train.shape[1],
                                      X_train.shape[2],1), activation = 'relu'))
model.add(MaxPooling2D(pool_size=(2,2)))
model.add(Conv2D(32, (3, 3), activation='relu'))
model.add(MaxPooling2D(pool_size=(2, 2)))
model.add(Dropout(0.2))
model.add(Flatten())
model.add(Dense(128, activation='relu'))
model.add(Dense(number_of_classes, activation='softmax'))

Instructions for updating:
Colocations handled automatically by placer.
Instructions for updating:
Please use `rate` instead of `keep_prob`. Rate should be set to `rate = 1 - keep_prob`.


In [25]:
# Compile model
model.compile(loss='categorical_crossentropy', optimizer=Adam(), metrics=['accuracy'])

In [26]:
# Fit the model
model.fit(X_train, y_train, validation_data=(X_test, y_test), epochs=10, batch_size=200)
# Save the model
model.save('/Users/elidangerfield/Desktop/mnistCNN.h5')

Instructions for updating:
Use tf.cast instead.
Train on 60000 samples, validate on 10000 samples
Epoch 1/10
60000/60000 [==============================] - 43s 709us/step - loss: 0.3023 - acc: 0.9119 - val_loss: 0.0711 - val_acc: 0.9792
Epoch 2/10
60000/60000 [==============================] - 44s 738us/step - loss: 0.0772 - acc: 0.9760 - val_loss: 0.0384 - val_acc: 0.9869
Epoch 3/10
60000/60000 [==============================] - 43s 723us/step - loss: 0.0545 - acc: 0.9838 - val_loss: 0.0325 - val_acc: 0.9897
Epoch 4/10
60000/60000 [==============================] - 43s 721us/step - loss: 0.0431 - acc: 0.9869 - val_loss: 0.0269 - val_acc: 0.9912
Epoch 5/10
60000/60000 [==============================] - 44s 726us/step - loss: 0.0371 - acc: 0.9883 - val_loss: 0.0260 - val_acc: 0.9917
Epoch 6/10
60000/60000 [==============================] - 45s 746us/step - loss: 0.0333 - acc: 0.9894 - val_loss: 0.0340 - val_acc: 0.9881
Epoch 7/10
60000/60000 [==============================] - 44s 729us/